- name: download packer archive
  get_url:
    url: "{{ packer.download_url }}"
    dest: "/usr/local/src/packer_{{ packer_version }}_linux_amd64.zip"
  register: download

- name: install packer
  unarchive:
    src: "/usr/local/src/packer_{{ packer_version }}_linux_amd64.zip"
    dest: "{{ packer.install_path }}"
    mode: 0755
  when: download|changed