common:
  locale: ja_JP.UTF-8
  timezone: Asia/Tokyo
  
docker:
  apt_key:
    - keyserver: hkp://ha.pool.sks-keyservers.net:80
      id: 58118E89F3A912897C070ADBF76221572C52609D
  repository: 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
  options:
    - docker_opts: --insecure-registry 192.168.33.14:5000
    
packer_version: 0.12.0
packer:
  download_url: https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip
  install_path: /usr/local/bin