common:
  locale: ja_JP.UTF-8
  timezone: Asia/Tokyo
  
docker:
  apt_key:
    - keyserver: hkp://ha.pool.sks-keyservers.net:80
      id: 58118E89F3A912897C070ADBF76221572C52609D
  repository: 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
  options:
    - docker_opts: --insecure-registry 192.168.33.14:5000