- name: apt-get install
  apt: name={{ item }} state=latest
  with_items:
    - apt-transport-https
    - ca-certificates
    
- name: add the new GPG key
  apt_key: keyserver={{ item.keyserver }} id={{ item.id }} state=present
  with_items: "{{ docker.apt_key }}"

- name: add docker deb package repository
  apt_repository:
    repo: "{{ docker.repository }}"
    state: present
  
- name: get uname -r
  shell: uname -r
  register: uname
  changed_when: false
  
- name: apt-get install
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - linux-image-extra-{{ uname.stdout }}
    - docker-engine
    
- name: set custom docker daemon options
  template:
    src=docker.service.j2
    dest=/lib/systemd/system/docker.service
  with_items: "{{ docker.options }}"
  notify: restart docker